version: '3.8' 

services:
  postgres:
    image: postgres:latest  
    container_name: postgres_instance_tps
    environment:
      POSTGRES_USER: mayank      
      POSTGRES_PASSWORD: root   
      POSTGRES_DB: tps          
    ports:
      - "5432:5432"                      
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:  
